import { chromium } from "playwright";
const b = await chromium.launch({ executablePath: "/chromium-1194/chrome-linux/chrome" });
const ctx = await b.newContext({ viewport:{width:375,height:812}, hasTouch:true, isMobile:true, deviceScaleFactor:2 });
const p = await ctx.newPage();
p.on("pageerror", e=>console.log("pageerror:", String(e).slice(0,300)));
await p.goto("http://localhost:8080/", {waitUntil:"domcontentloaded"});
await p.waitForTimeout(1500);
await p.evaluate(()=>localStorage.setItem("idx-basket-v1", JSON.stringify({stocks:[{id:"t1",ticker:"BBCA",shares:100,price:0,manualShares:false,manualPrice:false,freeFloat:null}],lastRefresh:null})));
await p.reload({waitUntil:"domcontentloaded"});
await p.waitForTimeout(3000);
console.log("labels:", JSON.stringify((await p.locator("button[aria-label]").evaluateAll(n=>n.map(x=>x.getAttribute("aria-label")))).slice(0,10)));
console.log("body:", (await p.locator("body").innerText()).slice(0,400));
await b.close();
